services:
  db:
    image: postgres:18
    container_name: liquidity_orchestrator_db
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin_password
      - POSTGRES_DB=postgres
    volumes:
      - ./init-dbs.sql:/docker-entrypoint-initdb.d/init-dbs.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  mock_providers:
    build:
      context: .
      dockerfile: docker_files/mock_providers.Dockerfile
    container_name: mock_providers
    ports:
      - "8001:8001"

