[project]
name = "liquidity-orchestrator-workspace"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = []

[tool.uv.workspace]
members = [
    "apps/*",
    "lib",
]

[tool.mypy]
ignore_missing_imports = true



[tool.ruff]
line-length = 120
preview = true

[tool.ruff.lint]
extend-select = ["E501"]  # check string length
select = [
    "E", # pycodestyle
    "F", # Pyflakes
    "I", # isort
    "Q", # quotes

]
[tool.ruff.lint.isort]
lines-after-imports = 2

[tool.ruff.format]
line-ending = "auto"
quote-style = "double"
exclude = ["*.pyi"]
