version: '3'

tasks:
  check:
    desc: Run all checks (tests, linter, type hints)
    deps: [ test:all, ruff:all, mypy:all ]
    aliases: [ c ]

  mypy:all:
    deps: [ mypy:apps, mypy:lib ]
  ruff:all:
    deps: [ ruff:apps, ruff:lib ]

  mypy:apps:
    desc: Run type checking for all apps
    cmds:
      - uv run mypy apps/
  mypy:lib:
    desc: Run type checking for lib
    cmds:
      - uv run mypy lib/

  ruff:apps:
    desc: Run linters and formatters for apps
    cmds:
      - uv run ruff check apps/ --fix
      - uv run ruff format apps/
  ruff:lib:
    desc: Run linters and formatters lib
    cmds:
      - uv run ruff check lib/ --fix
      - uv run ruff format lib/

  test:lib:
    desc: Run tests ONLY for the shared library
    dir: lib
    cmds:
      - uv run pytest

  test:orchestrator:
    desc: Run tests ONLY for the main application
    dir: apps/liquidity_orchestrator
    cmds:
      - uv run pytest

  test:mock:
    desc: Run tests ONLY for mock providers
    dir: apps/mock_providers
    cmds:
      - uv run pytest

  test:all:
    desc: Run all tests in the monorepo
    deps: [ test:lib, test:orchestrator, test:mock ]

  migration:upgrade:orchestrator:
    desc: To apply all migrations to the database (Liquidity Orchestrator)
    dir: apps/liquidity_orchestrator
    cmds:
      - uv run alembic upgrade head

  migration:create:orchestrator:
    desc: Create a new migration (Liquidity Orchestrator). Usage - task migration:create:orchestrator M="my migration message"
    dir: apps/liquidity_orchestrator
    cmds:
      - uv run alembic revision --autogenerate -m "{{.M}}"

  run:orchestrator:
    desc: Run main application (Liquidity Orchestrator)
    dir: apps/liquidity_orchestrator
    cmds:
      - uv run python -m liquidity_orchestrator.entrypoints.fastapi.main

  run:mock:
    desc: Run mock providers application
    dir: apps/mock_providers
    cmds:
      - uv run python -m mock_providers.entrypoints.fastapi.main

dotenv: [ '.env' ]
