[project]
name = "liquidity-orchestrator"
version = "0.1.0"
description = "Example of liquidity Orchestrator for Onramp/Offramp"
requires-python = ">=3.14"
dependencies = [
    "fastapi~=0.128.6",
    "uvicorn~=0.40.0",
    "pydantic-settings~=2.12.0",
    "cachetools~=7.0.1",
    "httpx~=0.28.1",
    "loguru~=0.7.3",
    "aiosqlite~=0.22.1",
    "alembic~=1.18.4",
    "opentelemetry-api~=1.39.1",
    "opentelemetry-instrumentation-fastapi~=0.60b1",
    "opentelemetry-instrumentation-sqlalchemy~=0.60b1",
    "opentelemetry-sdk~=1.39.1",
    "pytest~=9.0.2",
    "pytest-asyncio~=1.3.0",
    "sqlalchemy~=2.0.46",
    "pandas~=3.0.0",
    "mypy~=1.19.1",
    "ruff~=0.15.4",
    "diagrams>=0.25.1",
    "asyncpg>=0.31.0",
]

[dependency-groups]
dev = [
    "testcontainers[postgres]>=4.14.1",
    "types-cachetools>=6.2.0.20251022",
]

[tool.pytest.ini_options]
pythonpath = ["."]
asyncio_mode = "auto"
asyncio_default_test_loop_scope = "session"
