from typing import Any, Callable, Optional, Protocol, Sequence

from .models import Order, Outbox, Quote


class IRepository[ModelType](Protocol):
    async def get(self, record_id: int) -> Optional[ModelType]: ...

    async def get_all(self) -> Sequence[ModelType]: ...

    def add(self, instance: ModelType) -> None: ...

    async def update(self, record_id: int, **kwargs: Any) -> None: ...

    async def delete(self, instance: ModelType) -> None: ...


class IUnitOfWork(Protocol):
    @property
    def orders(self) -> IRepository[Order]: ...
    @property
    def quotes(self) -> IRepository[Quote]: ...
    @property
    def outbox(self) -> IRepository[Outbox]: ...

    async def commit(self) -> None: ...

    async def rollback(self) -> None: ...

    async def switch_session_context_for_task(self, func: Callable, *args: Any, **kwargs: Any) -> Any: ...

    async def __aenter__(self) -> "IUnitOfWork": ...

    async def __aexit__(self, exc_type, exc_val, exc_tb) -> None: ...
