[project]
name = "mock-providers"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "cachetools>=7.0.1,<8.0.0",
    "lib[fastapi]",
]

[tool.pytest.ini_options]
pythonpath = ["."]
asyncio_mode = "auto"
asyncio_default_test_loop_scope = "session"

[tool.uv.sources]
lib = { workspace = true }
