"""init

Revision ID: 5ba04ebd1cb4
Revises: 
Create Date: 2026-02-14 17:13:56.081633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ba04ebd1cb4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incoming_amount', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('outgoing_amount', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('incoming_account', sa.String(), nullable=False),
    sa.Column('outgoing_account', sa.String(), nullable=False),
    sa.Column('direction', sa.Enum('ON_RAMP', 'OFF_RAMP', name='quotedirection', native_enum=False), nullable=False),
    sa.Column('pair', sa.String(), nullable=False),
    sa.Column('quote_id', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'COMPLETED', 'FAILED', name='orderstatus', native_enum=False), server_default='NEW', nullable=False),
    sa.Column('provider_name', sa.String(), nullable=True),
    sa.Column('provider_ref', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quote_id')
    )
    op.create_table('quotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('direction', sa.Enum('ON_RAMP', 'OFF_RAMP', name='quotedirection', native_enum=False), nullable=False),
    sa.Column('pair', sa.String(), nullable=False),
    sa.Column('amount_in', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('amount_out', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('amount_fee', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('provider_name', sa.String(), nullable=False),
    sa.Column('valid_until', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('outbox',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('ORDER_FALLBACK', 'ORDER_COMPLETED', 'ORDER_FAILED', name='outboxeventtype', native_enum=False), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('outbox')
    op.drop_table('quotes')
    op.drop_table('orders')
    # ### end Alembic commands ###
